### ISSUE TITLE
php-to-7-aid/src/Console/Command/../../Solver/" directory does not exist

### ISSUE THREAD

**Issue by peterbowey** [gisostallenberg/phpTo7aid#1]
Executing `./php-to-7-aid run` (........ with various options ........)

```
  [InvalidArgumentException]
  The "php-to-7-aid/src/Console/Command/../../Solver/" directory does not exist.
```

Clues on the missing class?
Is it a function() to be implemented (later)?
There is very little in the source or docs to suggest what that is?

**Comment by gisostallenberg** [comment]
Thanks for pointing this out. It is due to the fact that the directory Solver is empty. In that case it will not get packed in to the .phar and will not be in git. I was not aware of that.
I added some checks to see if the directory exists.

Please understand this software is in early development and no real 'aid' is added yet. Please feel free in any way to contribute te checks (Scanners or Solvers) to aid in making code PHP7 compatible.

I added info on how to install the software and will be adding info on how to use it.

What where you trying to accomplish using this software?
